# pants.toml
[GLOBAL]
pants_version = "2.14.0"
backend_packages = ["pants.backend.python"]

[python]
interpreter_constraints = [">=3.8,<3.10"]
#enable_resolves = true
#resolves = { requirements = "lockfiles/requirements.txt" }
#lockfile_generator = "pex"

[python-bootstrap]
# We search for interpreters on both on the $PATH and in the `$(pyenv root)/versions` folder.
# Note the gotcha that the order of entries does not matter in this option, as Pants will consider
# all interpreters it finds and select a compatible one.
# So, if you're using macOS, you may want to leave off the <PATH> entry to avoid using the
# problematic system Pythons. See
# https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[python-infer]
string_imports = true

